version: '3.7'

services:
  base: &base
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - '..:/go/src/github.com/alvadorn/kyu_bot'
    working_dir: /go/src/github.com/alvadorn/kyu_bot

  test:
    <<: *base
    command: go test


