version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
      - image: circleci/redis:5-alpine3.9

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go mod vendor
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - codecov/upload:
        file: coverage.txt